[package]
name = "rust-bootloader"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
uefi = { version = "0.35.0", features = ["logger", "panic_handler"] }

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = "s"

[[bin]]
name = "bootx64"
path = "src/main.rs"
